---
title: "DARewiring Grapher"
author: "Yon Kwon"
date: "1/13/2024"
output: html_document
---

# Grapher for "Design Amidst (Social Behavior)" model

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(R.matlab)
library(tidyverse) # tibble (dataframe)
library(ggplot2) # Plot
library(tidyr) # gather()
library(scales) # pretty_breaks()
library(viridis)
library(ggpp) # Label text position
library(ggsci)
library(ggh4x) # facet nested
```

## Data Import
```{r data_file, eval=FALSE, include=FALSE}{r clear}
rm(list=ls()) # Cleaning R environment
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # Set SRC DIR as WD
file <- file.choose()
gc()
data <- readMat(file)
fig_id <- paste0(
  basename(file)
)

# label_mech <- c(
#   "atop('Homophily','(Characteristic)')",
#   "atop('Homophily','(Status)')",
#   'Network~Closure',
#   'Preferential~Attachment'
# )
label_mech <- c(
  "Homophily\n(Characteristic)",
  "Homophily\n(Status)",
  'Network\nClosure',
  'Preferential\nAttachment'
)
label_mech <- factor(
  label_mech, 
  levels = label_mech
)

label_scenario <- c(
  'Rewiring (Social)',
  'Rewiring (Random)',
  'No Rewiring'
)
label_scenario <- factor(
  label_scenario, 
  levels = label_scenario
)

fig_dpi <- 600
label_size <- 12
tick_label_size <- 10
```


## Figure 1 Compare with three scenarios
```{r fig1}
set_fig1_width = 6
set_fig1_height = 3.5
set_fig1_ylim = c(-.1, .9)

set_fig1_h <- 1
# set_fig1_span <- 1:data$para.g.span
set_fig1_span <- 1:(data$para.g.span)
set_fig1_connectivity <- 1
set_fig1_enforcement <- 1
set_fig1_t <- data$para.time

x_label <- 'Span of Control (S)'

y_label <- 'Firm Performance'
y_value_sc <- data$r.perf.avg
y_value_nr <- data$r.perf.nr.avg
y_value_rr <- data$r.perf.rr.avg

y_label <- 'Diversity of Belief'
y_value_sc <- data$r.disa.avg
y_value_nr <- data$r.disa.nr.avg
y_value_rr <- data$r.disa.rr.avg

# y_label <- 'Closeness Centralization'
# y_value_sc <- data$r.cent.avg
# y_value_nr <- data$r.cent.nr.avg
# y_value_rr <- data$r.cent.rr.avg
#
# y_label <- 'Overall Clustering'
# y_value_sc <- data$r.clus.avg
# y_value_nr <- data$r.clus.nr.avg
# y_value_rr <- data$r.clus.rr.avg
#
# y_label <- 'Network Efficiency'
# y_value_sc <- data$r.effi.avg
# y_value_nr <- data$r.effi.nr.avg
# y_value_rr <- data$r.effi.rr.avg

panel_label <- paste0('Panel ', LETTERS[1:20])
panel_label <- factor(panel_label, levels = panel_label)

df_fig1 <- data.frame()
panel_index <- 0
for (mc in 1:data$para.g.mech) {
  panel_index = panel_index + 1
  df_next <- data.frame(
    panel_label = panel_label[panel_index],
    mechanism = label_mech[mc],
    span = data$para.a.span[set_fig1_span],
    scenario = label_scenario[1],
    outcome = y_value_sc[mc, set_fig1_h, set_fig1_span, set_fig1_connectivity, set_fig1_enforcement, set_fig1_t]
  )
  
  df_fig1 <- rbind(df_fig1, df_next)
  df_next <- data.frame(
    panel_label = panel_label[panel_index],
    mechanism = label_mech[mc],
    span = data$para.a.span[set_fig1_span],
    scenario = label_scenario[2],
    outcome = y_value_rr[mc, set_fig1_h, set_fig1_span, set_fig1_connectivity, set_fig1_enforcement, set_fig1_t]
  )
  df_fig1 <- rbind(df_fig1, df_next)
  
  df_next <- data.frame(
    panel_label = panel_label[panel_index],
    mechanism = label_mech[mc],
    span = data$para.a.span[set_fig1_span],
    scenario = label_scenario[3],
    outcome = y_value_nr[mc, set_fig1_h, set_fig1_span, set_fig1_connectivity, set_fig1_enforcement, set_fig1_t]
  )
  df_fig1 <- rbind(df_fig1, df_next)
}

axes <- aes(
  x = span,
  y = outcome,
  color = scenario,
  shape = scenario
)

fig1 <- ggplot(data = df_fig1, mapping = axes) +
  # facet_grid(.~mechanism, labeller = label_parsed) +
  facet_grid(. ~ mechanism) +
  # geom_text_npc(aes(label = panel_label, npcx='right', npcy='bottom'), size=4, colour='black') +
  geom_line(alpha = .9, size = .5) +
  geom_point(size = 2) +
  scale_shape_manual(values = c(16, 1, 4)) +
  scale_linetype_manual(values = c('solid', 'dotted', 'dashed')) +
  scale_x_continuous(expand = c(0, .02)) +
  scale_y_continuous(expand = c(0, .02)) +
  labs(x = x_label, y = y_label) +
  scale_color_npg() +
  theme_bw() +
  theme(
    text = element_text(
      # family = windowsFonts()$serif,
      size = label_size, color = 'black'
    ),
    axis.title = element_text(size = label_size, color = 'black'),
    axis.text = element_text(size = tick_label_size, color = 'black'),
    axis.text.x = element_text(color = 'black'),
    strip.background = element_blank(),
    strip.placement = 'outside',
    strip.text = element_text(color = 'black'),
    panel.spacing = unit(1, 'lines'),
    legend.title = element_blank(),
    legend.position = 'bottom'
  )

fig1
ggsave(
  paste0(
    fig_id, '_',
    'fig1_', y_label,
    'span', paste0(data$para.a.span[set_fig1_span], collapse = ","),
    'c', data$para.a.conn[set_fig1_connectivity],
    'e', data$para.a.enfo[set_fig1_enforcement],
    't', set_fig1_t,
    '.png'
  ),
  plot = fig1,
  units = 'in',
  width = set_fig1_width,
  height = set_fig1_height,
  dpi = fig_dpi
)
```




## Figure 2 Optimal Structure
```{r fig2}
set_fig2_width = 6
set_fig2_height = 3
set_fig2_ylim = c(-.1, .9)

set_fig2_h <- 1
set_fig2_span <- data$para.a.span
set_fig2_span <- (as.vector(data$para.n) - set_fig2_span - 1)/set_fig2_span

set_fig2_t <- data$para.time
set_fig2_t <- 200

x_label <-'Rewiring Mechanism'
y_label <- 'Optimal Span of Control'
y_value_sc <- data$r.perf.avg
y_value_nr <- data$r.perf.nr.avg
y_value_rr <- data$r.perf.rr.avg

panel_label <- paste0('Panel ', LETTERS[1:20])
panel_label <- factor(panel_label, levels=panel_label)

df_fig2 <- data.frame()
panel_index <- 0
for( mc in 1:data$para.g.mech ){
  panel_index = panel_index+1
  df_next <- data.frame(
    panel_label = panel_label[panel_index],
    mechanism = label_mech[mc],
    scenario = label_scenario[1],
    outcome = data$para.a.span[which.max(y_value_sc[mc, set_fig2_h, , set_fig2_t])]
  )
  df_fig2 <- rbind(df_fig2, df_next)
  df_next <- data.frame(
    panel_label = panel_label[panel_index],
    mechanism = label_mech[mc],
    scenario = label_scenario[2],
    outcome = data$para.a.span[which.max(y_value_nr[mc, set_fig2_h, , set_fig2_t])]
  )
  df_fig2 <- rbind(df_fig2, df_next)
  df_next <- data.frame(
    panel_label = panel_label[panel_index],
    mechanism = label_mech[mc],
    scenario = label_scenario[3],
    outcome = data$para.a.span[which.max(y_value_rr[mc, set_fig2_h, , set_fig2_t])]
  )
  df_fig2 <- rbind(df_fig2, df_next)
}

axes <- aes(
  fill = scenario,
  x = mechanism,
  y = outcome
)

fig2 <- ggplot(data = df_fig2, mapping = axes) +
  # facet_grid(.~mechanism, labeller = label_parsed) +
  # geom_text_npc(aes(label = panel_label, npcx='right', npcy='bottom'), size=4, colour='black') +
  geom_bar(alpha = .9, position = 'dodge', stat = 'identity', color = NA) +
  scale_y_continuous(expand=c(0,0), ) +
  labs(x = x_label, y = y_label) +
  scale_fill_npg(labels = parse_format()) +
  theme_bw()+
  theme(
    text=element_text(
      # family = windowsFonts()$serif,
      size=label_size, color='black'
    ),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    axis.text.x = element_text(color = 'black'),
    strip.background = element_blank(),
    strip.placement = 'outside',
    strip.text = element_text(color = 'black'),
    panel.spacing = unit(1, 'lines'),
    legend.title = element_blank(),
    legend.position = 'bottom'
  )

fig2
ggsave(
  paste0(fig_id, '_',
         'fig2_',
         y_label,
         'span', paste0(data$para.a.span[set_fig2_span], collapse = ","),
         't', set_fig2_t,
         '.png'
         ),
  plot = fig2,
  units = 'in', 
  width = set_fig2_width,
  height = set_fig2_height,
  dpi = fig_dpi
)
```




## Longitudinal Pattern
```{r figa}
set_figa_width = 6
set_figa_height = 5
set_figa_ylim = c(-.1, .9)

set_figa_h <- 1
set_figa_span <- 1:(data$para.g.span-1)
set_figa_span <- 1
set_figa_connectivity <- 1:data$para.g.conn
set_figa_enforcement <- 1:data$para.g.enfo
set_figa_t <- 1:data$para.time

x_label <- expression(Span ~ of ~ Control ~ (italic(sigma)))

y_label <- 'Firm Performance'
y_value_sc <- data$r.perf.avg
y_value_nr <- data$r.perf.nr.avg
y_value_rr <- data$r.perf.rr.avg

# y_label <- 'Closeness Centralization'
# y_value_sc <- data$r.cent.avg
# y_value_nr <- data$r.cent.nr.avg
# y_value_rr <- data$r.cent.rr.avg
#
# y_label <- 'Overall Clustering'
# y_value_sc <- data$r.clus.avg
# y_value_nr <- data$r.clus.nr.avg
# y_value_rr <- data$r.clus.rr.avg
#
# y_label <- 'Network Efficiency'
# y_value_sc <- data$r.effi.avg
# y_value_nr <- data$r.effi.nr.avg
# y_value_rr <- data$r.effi.rr.avg

y_label <- 'Number of Rewiring'
y_value_sc <- data$r.rewi.avg
y_value_nr <- data$r.rewi.avg
y_value_rr <- data$r.rewi.avg

panel_label <- paste0('Panel ', LETTERS[1:20])
panel_label <- factor(panel_label, levels = panel_label)

connectivity_label <- paste0('C=', data$para.a.conn)
connectivity_label <- factor(connectivity_label, levels = connectivity_label)

enforcement_label <- paste0('E=', data$para.a.enfo)
enforcement_label <- factor(enforcement_label, levels = enforcement_label)

df_figa <- data.frame()
panel_index <- 0
for (mc in 1:data$para.g.mech) {
  for( s in set_figa_span ){
    for (c in set_figa_connectivity) {
      for (e in set_figa_enforcement) {
        panel_index = panel_index + 1
        df_next <- data.frame(
          panel_label = panel_label[panel_index],
          mechanism = label_mech[mc],
          span = data$para.a.span[s],
          scenario = label_scenario[1],
          connectivity = connectivity_label[c],
          enforcement = enforcement_label[e],
          time = set_figa_t,
          outcome = y_value_sc[mc, set_figa_h, s, c, e, set_figa_t]
        )
        
        # df_figa <- rbind(df_figa, df_next)
        # df_next <- data.frame(
        #   panel_label = panel_label[panel_index],
        #   mechanism = label_mech[mc],
        #   span = data$para.a.span[set_figa_span],
        #   scenario = label_scenario[2],
        #   outcome = y_value_rr[mc, set_figa_h, set_figa_span, set_figa_connectivity, set_figa_enforcement, set_figa_t]
        # )
        # df_figa <- rbind(df_figa, df_next)
        # 
        # df_next <- data.frame(
        #   panel_label = panel_label[panel_index],
        #   mechanism = label_mech[mc],
        #   span = data$para.a.span[set_figa_span],
        #   scenario = label_scenario[3],
        #   outcome = y_value_nr[mc, set_figa_h, set_figa_span, set_figa_connectivity, set_figa_enforcement, set_figa_t]
        # )
        df_figa <- rbind(df_figa, df_next)
      }
    }
  }
}

axes <- aes(
  x = time,
  y = outcome,
  color = span,
  shape = scenario
)

figa <- ggplot(data = df_figa, mapping = axes) +
  # facet_grid(.~mechanism, labeller = label_parsed) +
  facet_nested(enforcement ~ mechanism + connectivity) +
  # geom_text_npc(aes(label = panel_label, npcx='right', npcy='bottom'), size=4, colour='black') +
  geom_line(alpha = .9, size = .1) +
  # geom_point(size = 2) +
  # scale_shape_manual(values = c(16, 1, 4),
  #                    labels = parse_format()) +
  # scale_linetype_manual(values = c('solid', 'dotted', 'dashed'),
  #                       labels = parse_format()) +
  # scale_color_npg() +
  scale_x_continuous(expand = c(0, .02)) +
  scale_y_continuous(expand = c(0, .02)) +
  labs(x = x_label, y = y_label) +
  theme_bw() +
  theme(
    text = element_text(# family = windowsFonts()$serif,
    size = label_size, color = 'black'),
    axis.title = element_text(size = label_size, color = 'black'),
    axis.text = element_text(size = tick_label_size, color = 'black'),
    axis.text.x = element_text(color = 'black'),
    strip.background = element_blank(),
    strip.placement = 'outside',
    strip.text = element_text(color = 'black'),
    panel.spacing = unit(1, 'lines'),
    # legend.title = element_blank(),
    legend.position = 'bottom'
  )

figa
ggsave(
  paste0(
    fig_id,
    '_',
    'figa_',
    y_label,
    'span',
    paste0(data$para.a.span[set_figa_span], collapse = ","),
    't',
    set_figa_t,
    '.png'
  ),
  plot = figa,
  units = 'in',
  width = set_figa_width,
  height = set_figa_height,
  dpi = fig_dpi
)
```


