package DAFormation;

import java.io.FileWriter;
import java.io.IOException;
import jdk.jfr.Description;
import org.apache.commons.math3.random.MersenneTwister;
import org.apache.commons.math3.random.RandomGenerator;
import org.apache.commons.math3.util.FastMath;

public class Scenario {

  RandomGenerator r;
  NetworkAnalyzer na;

  int socialMechanism;

  boolean isRewiring;
  boolean isHomophilyOnChar;
  boolean isHomophilyOnStat;
  boolean isNetworkClosure;
  boolean isPreferentialAttachment;
  boolean isRandomRewiring;

  int[] focalIndexArray;
  int[] targetIndexArray;

  int observationScope;

  double strength;      //Strength of social behavior
  int span;          //Span of control
  double connectivity;      //Connectivity across hierarchy

  boolean[] reality;
  int[] realityBundleID;
  boolean[][] beliefOf;
  boolean[][] typeOf;

  int[] performance;

  int[] levelOf;
  double levelRange;
  boolean[][] network;
  boolean[][] networkFormal;
  boolean[][] networkInformal;
  boolean[][] observationStructure;
  int[] degree;
  int[] degreeFormal;
  int[] degreeInformal;
  double[][] differenceOf;
  double[] differenceSum;

  double[][] neighborScore;
  double[] neighborhoodScore;
  boolean[] satisfied;

  int numFormation;
  double performanceAvg;
  double disagreementAvg;

  double diameter;
  double averagePathLength;
  double networkEfficiency;
  double overallClustering;
  double overallCentralization;

  double satisfactionRate;

  Scenario(int socialMechanism, double strength, int span, double connectivity) {
    r = new MersenneTwister();

    this.socialMechanism = socialMechanism;
    switch (socialMechanism) {
      case 0 -> isHomophilyOnChar = true;
      case 1 -> isHomophilyOnStat = true;
      case 2 -> isNetworkClosure = true;
      case 3 -> isPreferentialAttachment = true;
    }

    focalIndexArray = new int[Main.N];
    for (int n = 0; n < Main.N; n++) {
      focalIndexArray[n] = n;
    }
    targetIndexArray = focalIndexArray.clone();

    this.strength = strength;
    this.span = span;
    this.connectivity = connectivity;

    this.observationScope = Main.OBSERVATION_SCOPE;

    isRewiring = true;
    isRandomRewiring = false;

    initialize();
  }

  public Scenario getClone() {
    Scenario clone = new Scenario(this.socialMechanism, this.strength, this.span, this.connectivity);

    clone.reality = this.reality.clone();
    clone.realityBundleID = this.realityBundleID.clone();
    clone.beliefOf = new boolean[Main.N][];
    clone.typeOf = new boolean[Main.N][];
    clone.performance = this.performance.clone();

    clone.networkFormal = new boolean[Main.N][];
    clone.networkInformal = new boolean[Main.N][];
    clone.network = new boolean[Main.N][];
    clone.na = new NetworkAnalyzer(clone.network);

    clone.degreeFormal = this.degreeFormal.clone();
    clone.degreeInformal = this.degreeInformal.clone();
    clone.degree = this.degree.clone();

    clone.differenceOf = new double[Main.N][];
    clone.differenceSum = this.differenceSum.clone();
    clone.satisfied = this.satisfied.clone();

    clone.numFormation = this.numFormation;
    clone.performanceAvg = this.performanceAvg;
    clone.disagreementAvg = this.disagreementAvg;
    clone.satisfactionRate = this.satisfactionRate;

    for (int focal = 0; focal < Main.N; focal++) {
      clone.beliefOf[focal] = this.beliefOf[focal].clone();
      clone.typeOf[focal] = this.typeOf[focal].clone();

      clone.networkFormal[focal] = this.networkFormal[focal].clone();
      clone.networkInformal[focal] = this.networkInformal[focal].clone();
      clone.network[focal] = this.network[focal].clone();

      clone.differenceOf[focal] = this.differenceOf[focal].clone();
    }

    return clone;
  }

  public Scenario getClone(boolean isRewiring, boolean isRandomRewiring) {
    Scenario clone = getClone();
    clone.setNetworkParams(isRewiring, isRandomRewiring);
    return clone;
  }

  void setNetworkParams(boolean isRewiring, boolean isRandomRewiring) {
    this.isRewiring = isRewiring;
    this.isRandomRewiring = isRandomRewiring;
  }

  public void copyRealityOf(Scenario src) {
    reality = src.reality.clone();
    realityBundleID = src.realityBundleID.clone();
  }

  private void initialize() {
    initializeNetwork();
    initializeEntity(); //TypeOf depends on the network (membership)
    initializeOutcome();
  }

  private void initializeNetwork() {
    network = new boolean[Main.N][Main.N];
    networkFormal = new boolean[Main.N][Main.N];
    networkInformal = new boolean[Main.N][Main.N];
    levelOf = new int[Main.N];

    degreeFormal = new int[Main.N];
    degreeInformal = new int[Main.N];
    degree = new int[Main.N];

    int upperStart = 0;
    int upperEnd;
    int lowerStart = 1;
    //@ 230910 This code is generated by ChatGPT - Check validity
    for (; ; ) {
      upperEnd = FastMath.min(upperStart + (int) FastMath.pow(span, upperStart / span), Main.N);
      // For all nodes at the current depth, assign subordinates
      for (int upper = upperStart; upper < upperEnd; upper++) {
        int lowerEnd = FastMath.min(lowerStart + span, Main.N);
        for (int lower = lowerStart; lower < lowerEnd; lower++) {
          network[upper][lower] = true;
          network[lower][upper] = true;
          networkFormal[upper][lower] = true;
          networkFormal[lower][upper] = true;
          degree[upper]++;
          degree[lower]++;
          degreeFormal[upper]++;
          degreeFormal[lower]++;
        }
        if (Main.LINK_LEVEL) {
          int lowerNum = lowerEnd - lowerStart;
          if (lowerStart == lowerEnd) {
            continue;
          }
          for (int i = 0; i < lowerNum; i++) {
            int focal = lowerStart + i;
            int target = lowerStart + (i + 1) % lowerNum;
            if (focal == target) {
              break;
            }
            network[focal][target] = true;
            network[target][focal] = true;
            networkFormal[focal][target] = true;
            networkFormal[target][focal] = true;
            degree[focal]++;
            degree[target]++;
            degreeFormal[focal]++;
            degreeFormal[target]++;
          }
        }
        lowerStart = lowerEnd;
      }
      if (lowerStart == Main.N) {
        break;
      }
      upperStart = upperEnd;
    }

    int levelStart = 0;
    int levelEnd = 1;
    int levelNow = 1;
    for (; ; ) {
      for (int i = levelStart; i < levelEnd; i++) {
        levelOf[i] = levelNow;
      }
      levelStart = levelEnd;
      levelEnd = FastMath.min(Main.N, levelEnd + (int) FastMath.pow(span, levelNow));
      if (levelStart == Main.N) {
        levelRange = levelNow;
        break;
      }
      levelNow++;
    }
    levelRange -= levelOf[0];

    //Additional Connection
    for (int focal = 0; focal < Main.N; focal++) {
      for (int target = focal; target < Main.N; target++) {
        if (!network[focal][target] &&
            degree[focal] < Main.MAX_DEGREE &&
            degree[target] < Main.MAX_DEGREE &&
            focal != target) {
          if (r.nextDouble() < connectivity) {
            network[focal][target] = true;
            network[target][focal] = true;
            networkFormal[focal][target] = true;
            networkFormal[target][focal] = true;
            degree[focal]++;
            degree[target]++;
            degreeFormal[focal]++;
            degreeFormal[target]++;
          }
        }
      }
    }

    na = new NetworkAnalyzer(network);
    setObservationStructure();
  }

  private void initializeEntity() {
    reality = new boolean[Main.M];
    realityBundleID = new int[Main.M];
    typeOf = new boolean[Main.N][Main.L];
    beliefOf = new boolean[Main.N][Main.M];

    for (int bundle = 0; bundle < Main.M_OF_BUNDLE; bundle++) {
      int baseIndex = bundle * Main.M_IN_BUNDLE;
      int endIndex = (bundle + 1) * Main.M_IN_BUNDLE;
      for (int m = baseIndex; m < endIndex; m++) {
        reality[m] = r.nextBoolean();
        realityBundleID[m] = bundle;
      }
    }

    for (int focal = 0; focal < Main.N; focal++) {
      for (int l = 0; l < Main.L; l++) {
        typeOf[focal][l] = r.nextBoolean();
      }
      for (int m = 0; m < Main.M; m++) {
        beliefOf[focal][m] = r.nextBoolean();
      }
    }
  }

  private void initializeOutcome() {
    performance = new int[Main.N];

    differenceOf = new double[Main.N][Main.N];
    differenceSum = new double[Main.N];
    satisfied = new boolean[Main.N];

    setPerformance();
    doEvaluateNeighbor();
    setOutcome();
  }

  void stepForward() {
    if (isRewiring) {
      doEvaluateNeighbor();
      setObservationStructure();
      doFormation();
    }
    doLearning();
  }

  void stepForward(int numRewiring) {
    if (isRewiring) {
      setObservationStructure();
      doFormation(numRewiring);
    }
    doLearning();
  }

  void setOutcome() {
    performanceAvg = 0;
    disagreementAvg = 0;
    satisfactionRate = 0;
    na.setNetworkMetrics();
    diameter = na.getDiameter();
    averagePathLength = na.getAveragePathLength();
    networkEfficiency = na.getNetworkEfficiency();
    overallClustering = na.getOverallClustering();
    overallCentralization = na.getOverallClosenessCentralization();

    for (int focal = 0; focal < Main.N; focal++) {
      performanceAvg += performance[focal];
      satisfactionRate += satisfied[focal] ? 1 : 0;
      for (int target = focal; target < Main.N; target++) {
        for (int m = 0; m < Main.M; m++) {
          if (beliefOf[focal][m] != beliefOf[target][m]) {
            disagreementAvg++;
          }
        }

      }
    }
    performanceAvg /= Main.M_N;
    disagreementAvg /= Main.M_N_DYAD;
    satisfactionRate /= Main.N;
  }

  double getNeighborScoreHomophilyOnChar(int focal, int target) {
    double neighborScore = 0;
    for (int ch = 0; ch < Main.L; ch++) {
      if (typeOf[focal][ch] == typeOf[target][ch]) {
        neighborScore++;
      }
    }
    return neighborScore / (double) Main.L;
  }

  double getNeighborScoreHomophilyOnStatus(int focal, int target) {
    return 1D - FastMath.abs(levelOf[focal] - levelOf[target]) / levelRange;
  }

  double getNeighborScoreNetworkClosure(int focal, int target) {
    double neighborScore = 0;
    for (int i = 0; i < Main.N; i++) {
      if (focal == i || target == i) {
        continue;
      }
      if (network[focal][i] && network[target][i]) {
        neighborScore++;
//        System.out.println(
//            focal+ " " + target + " to " + i +
//            network[focal][i] + " " + network[target][i] + " -> "+ neighborScore
//        );
      }
    }
    return neighborScore / (double) (degree[focal] - 1D);
  }

  double getNeighborScoreNetworkClosure(int focal, int target, boolean[][] network) {
    double neighborScore = 0;
    for (int i = 0; i < Main.N; i++) {
      if (focal == i || target == i) {
        continue;
      }
      if (network[focal][i] && network[target][i]) {
        neighborScore++;
      }
    }
    return neighborScore / (double) degree[focal];
  }

  double getNeighborScorePreferentialAttachement(int focal, int target) {
    int degreeMin = degree[focal];
    int degreeMax = degree[focal];
    for (int observable = 0; observable < Main.N; observable++) {
      if (observationStructure[focal][observable]) {
        if (degree[observable] > degreeMax) {
          degreeMax = degree[observable];
        }else if (degree[observable] < degreeMin) {
          degreeMin = degree[observable];
        }
      }
    }
    return (double) (degree[target] - degreeMin) / (double) (degreeMax - degreeMin);
  }

  void doEvaluateNeighbor() {
    neighborScore = new double[Main.N][Main.N];
    neighborhoodScore = new double[Main.N];
    if (isHomophilyOnChar) {
      for (int focal : focalIndexArray) {
        for (int target = focal; target < Main.N; target++) {
          if (!network[focal][target]) {
            continue;
          }
          neighborScore[focal][target] = getNeighborScoreHomophilyOnChar(focal, target);
          neighborScore[target][focal] = neighborScore[focal][target];
          neighborhoodScore[focal] += neighborScore[focal][target];
          neighborhoodScore[target] += neighborScore[target][focal];
        }
      }
    } else if (isHomophilyOnStat) {
      for (int focal : focalIndexArray) {
        for (int target = focal; target < Main.N; target++) {
          if (!network[focal][target]) {
            continue;
          }
          neighborScore[focal][target] = getNeighborScoreHomophilyOnStatus(focal, target);
          neighborScore[target][focal] = neighborScore[focal][target];
          neighborhoodScore[focal] += neighborScore[focal][target];
          neighborhoodScore[target] += neighborScore[target][focal];
        }
      }
    } else if (isNetworkClosure) {
      for (int focal : focalIndexArray) {
        for (int target = focal; target < Main.N; target++) {
          if (!network[focal][target]) {
            continue;
          }
          neighborScore[focal][target] = getNeighborScoreNetworkClosure(focal, target);
          // The number of common interactions is the same for both individuals.
          neighborScore[target][focal] = neighborScore[focal][target] * (degree[focal] - 1D) / (degree[target] - 1D);
          neighborhoodScore[focal] += neighborScore[focal][target];
          neighborhoodScore[target] += neighborScore[target][focal];
        }
      }
    } else if (isPreferentialAttachment) {
      for (int focal : focalIndexArray) {
        for (int target = focal; target < Main.N; target++) {
          if (!network[focal][target]) {
            continue;
          } else {
            neighborScore[focal][target] = getNeighborScorePreferentialAttachement(focal, target);
            neighborScore[target][focal] = getNeighborScorePreferentialAttachement(target, focal);
            neighborhoodScore[focal] += neighborScore[focal][target];
            neighborhoodScore[target] += neighborScore[target][focal];
          }
        }
      }
    }
    for (int focal = 0; focal < Main.N; focal++) {
      neighborhoodScore[focal] /= (double) degree[focal];
      // Neighborhood score is higher than desired score = strength
      satisfied[focal] = neighborhoodScore[focal] >= strength;
    }
  }

  @Description("Returns similarity in a fraction [0, 1]")
  double getHomogeneityBetween(int focal, int target) {
    double homogeneityCharacteristic = 0;
    double homogeneityBelief = 0;
    if (Main.WEIGHT_ON_CHARACTERISTIC > 0D) {
      for (int l = 0; l < Main.L; l++) {
        if (typeOf[focal][l] == typeOf[target][l]) {
          homogeneityCharacteristic++;
        }
      }
      homogeneityCharacteristic = Main.WEIGHT_ON_CHARACTERISTIC * homogeneityCharacteristic / (double) Main.L;
    }
    if (Main.WEIGHT_ON_BELIEF > 0D) {
      for (int m = 0; m < Main.M; m++) {
        if (beliefOf[focal][m] == beliefOf[target][m]) {
          homogeneityBelief++;
        }
      }
      homogeneityBelief /= Main.WEIGHT_ON_BELIEF * homogeneityBelief / (double) Main.M;
    }
    return homogeneityCharacteristic + homogeneityBelief;
  }

  void setObservationStructure() {
    //Revised with matrix multiplication - Test its validity
    observationStructure = new boolean[Main.N][];
    boolean[][] networkInDegreeLeft = new boolean[Main.N][];
    boolean[][] networkInDegreeRight;
    for (int focal = 0; focal < Main.N; focal++) {
      networkInDegreeLeft[focal] = network[focal].clone();
      observationStructure[focal] = network[focal].clone();
    }
    for (int d = 1; d < observationScope; d++) { // Degree
      networkInDegreeRight = new boolean[Main.N][Main.N];
      for (int row = 0; row < Main.N; row++) {
        for (int col = 0; col < Main.N; col++) {
          for (int i = 0; i < Main.N; i++) {
            if (networkInDegreeLeft[row][i] && network[i][col]) {
              networkInDegreeRight[row][col] = true;
              observationStructure[row][col] = true;
              break;
            }
          }
        }
      }
      networkInDegreeLeft = networkInDegreeRight;
    }
  }

  void doFormation() {
    numFormation = 0;
    boolean[] hasNewTie = new boolean[Main.N];
    shuffleFisherYates(focalIndexArray);
    for (int focal : focalIndexArray) {
      if (degree[focal] >= Main.MAX_DEGREE ||
          hasNewTie[focal] ||
          satisfied[focal]
      ) {
        continue;
      }
      //Selection of a new neighbor to connect
      shuffleFisherYates(targetIndexArray);
      for (int target : targetIndexArray) {
        if (!observationStructure[focal][target] || // If the target is outside the observation structure
            degree[target] >= Main.MAX_DEGREE ||
            hasNewTie[target] || // If the target already has a new tie
            network[focal][target] || // If the target is already a neighbor of the focal
            satisfied[target] || // If the target is already satisfied
            focal == target // If the target is focal herself
        ) {
          continue;
        }
        double targetPreferenceScore = Double.NaN;
        boolean[][] networkAlt = new boolean[Main.N][];
        if (isHomophilyOnChar) {
          targetPreferenceScore = getNeighborScoreHomophilyOnChar(focal, target);
        } else if (isHomophilyOnStat) {
          targetPreferenceScore = getNeighborScoreHomophilyOnStatus(focal, target);
        } else if (isNetworkClosure) {
          targetPreferenceScore = getNeighborScoreNetworkClosure(focal, target);
        } else if (isPreferentialAttachment) {
          targetPreferenceScore = getNeighborScorePreferentialAttachement(focal, target);
        }
        if (targetPreferenceScore < neighborhoodScore[focal]) {
          //Pref score of target is lower than focal's average neighborhoods score
          continue;
        }
        //Checking for mutual agreement
        double focalPreferenceScore = Double.NaN;
        if (isHomophilyOnChar) {
          focalPreferenceScore = targetPreferenceScore;
        } else if (isHomophilyOnStat) {
          focalPreferenceScore = targetPreferenceScore;
        } else if (isNetworkClosure) {
          focalPreferenceScore = targetPreferenceScore / (degree[focal] - 1D) * (degree[target] - 1D);
        } else if (isPreferentialAttachment) {
          focalPreferenceScore = getNeighborScorePreferentialAttachement(target, focal);
        }
        if (focalPreferenceScore < neighborhoodScore[target]) {
          //Pref score of focal is lower than target's average neighborhoods score
          continue;
        }
        // Forming tie
        network[focal][target] = true;
        network[target][focal] = true;
        networkInformal[focal][target] = true;
        networkInformal[target][focal] = true;
        degree[target]++;
        degreeInformal[target]++;
        hasNewTie[focal] = true;
        hasNewTie[target] = true;
        numFormation++;
        // Reset Neighborhood Score
        doEvaluateNeighbor();
        //Occurs at most once for each individual
        break;
      }
    }
  }

  void doFormation(int numRewiring) {
    //Random rewiring
    int numFormationLeft = numRewiring;
    boolean[] hasNewTie = new boolean[Main.N];
    shuffleFisherYates(focalIndexArray);
    for (int focal : focalIndexArray) {
      if (numFormationLeft == 0) {
        break;
      }
      if (hasNewTie[focal] ||
          degree[focal] >= Main.MAX_DEGREE) {
        continue;
      }
      shuffleFisherYates(targetIndexArray);
      for (int target : targetIndexArray) {
        if (network[focal][target] || // If the target is already a neighbor of the focal
            hasNewTie[target] || // If the target already has a new tie
            !observationStructure[focal][target] || // If the target is outside the observation structure
            degree[target] >= Main.MAX_DEGREE ||
            focal == target // If the target is focal herself
        ) {
          continue;
        }
        hasNewTie[focal] = true;
        hasNewTie[target] = true;
        // Forming tie
        networkInformal[focal][target] = true;
        networkInformal[target][focal] = true;
        network[focal][target] = true;
        network[target][focal] = true;
        degreeInformal[target]++;
        degree[target]++;
        numFormationLeft--;
        break;
      }
    }
  }

  void doLearning() {
    boolean[][] beliefOfUpdated = new boolean[Main.N][Main.M];
    for (int focal = 0; focal < Main.N; focal++) {
      int[] majorityOpinion = new int[Main.M];
      for (int target = 0; target < Main.N; target++) {
        if (network[focal][target] && performance[target] > performance[focal]) {
          for (int m = 0; m < Main.M; m++) {
            majorityOpinion[m] += beliefOf[target][m] ? 1 : -1;
          }
        }
      }
      for (int m = 0; m < Main.M; m++) {
        if (r.nextDouble() < Main.P_LEARNING) {
          if (majorityOpinion[m] > 0) {
            beliefOfUpdated[focal][m] = true;
          } else if (majorityOpinion[m] < 0) {
            beliefOfUpdated[focal][m] = false;
          } else {
            beliefOfUpdated[focal][m] = beliefOf[focal][m];
          }
        } else {
          beliefOfUpdated[focal][m] = beliefOf[focal][m];
        }
      }
    }
    beliefOf = beliefOfUpdated;
    for (int focal = 0; focal < Main.N; focal++) {
      setPerformance(focal);
    }
  }

  int getPerformance(int focal) {
    //VERRY WEIRD... COPY FROM ALTRUISM MODEL AND TEST
    int performanceNow = 0;
    boolean[] beliefOfFocal = beliefOf[focal];
    for (int bundle = 0; bundle < Main.M_OF_BUNDLE; bundle++) {
      int countMInBundle = 0;
      boolean matchAll = true;
      for (int m = 0; m < Main.M; m++) {
        if (realityBundleID[m] == bundle) {
          countMInBundle++;
          if (beliefOfFocal[m] != reality[m]) {
            matchAll = false;
            break;
          }
        }
      }
      if (matchAll) {
        performanceNow += countMInBundle;
      }
    }
    return performanceNow;
  }

  void setPerformance(int focal) {
    performance[focal] = getPerformance(focal);
  }

  void setPerformance() {
    for (int focal = 0; focal < Main.N; focal++) {
      setPerformance(focal);
    }
  }

  void printCSV(String fileName) {
    try {
      FileWriter csvWriter;
      csvWriter = new FileWriter(fileName + ".csv");
      csvWriter.append("SOURCE");
      csvWriter.append(",");
      csvWriter.append("TARGET");
      csvWriter.append(",");
      for (int l = 0; l < Main.L; l++) {
        csvWriter.append("SOURCE_TYPE" + l);
        csvWriter.append(",");
      }
      csvWriter.append("TIE_ENFORCED");
      csvWriter.append(",");
      csvWriter.append("L");
      csvWriter.append("\n");

      //Edge
      for (int focal = 0; focal < Main.N; focal++) {
        for (int target = focal; target < Main.N; target++) {
          if (focal == target) {
            continue;
          }
          if (network[focal][target]) {
//            csvWriter.append("SOURCE");
            csvWriter.append(Integer.toString(focal));
            csvWriter.append(",");

//            csvWriter.append("TARGET");
            csvWriter.append(Integer.toString(target));
            csvWriter.append(",");

//            csvWriter.append("SOURCE_TYPE");
            for (int l = 0; l < Main.L; l++) {
              csvWriter.append(typeOf[focal][l] ? "true" : "false");
              csvWriter.append(",");
            }

//            csvWriter.append("TIE_ENFORCED");
            csvWriter.append(Boolean.toString(networkFormal[focal][target]));
            csvWriter.append(",");

//            csvWriter.append("L");
            csvWriter.append(Integer.toString(Main.L));
            csvWriter.append("\n");
          }
        }
      }

      //Individual
      for (int focal = 0; focal < Main.N; focal++) {
//        csvWriter.append("SOURCE");
        csvWriter.append(Integer.toString(focal));
        csvWriter.append(",");

//        csvWriter.append("TARGET");
        csvWriter.append(",");

//        csvWriter.append("SOURCE_TYPE");
        for (int l = 0; l < Main.L; l++) {
          csvWriter.append(typeOf[focal][l] ? "true" : "false");
          csvWriter.append(",");
        }

//        csvWriter.append("TIE_ENFORCED");
        csvWriter.append(",");

//        csvWriter.append("L");
        csvWriter.append(Integer.toString(Main.L));
        csvWriter.append("\n");
      }

      csvWriter.flush();
      csvWriter.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  void shuffleFisherYates(int[] nArray) {
    for (int i = Main.N - 1; i > 0; i--) {
      int j = r.nextInt(i + 1);
      int temp = nArray[i];
      nArray[i] = nArray[j];
      nArray[j] = temp;
    }
  }
}
